name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint/Compile (no API calls)
        run: |
          python -m compileall -q .
          python - << 'PY'
          import importlib.util
          import sys
          for path in ['coingecko_fetch.py']:
              spec = importlib.util.spec_from_file_location('mod', path)
              mod = importlib.util.module_from_spec(spec)
              spec.loader.exec_module(mod)
          print('Import OK')
          PY


